### ISSUE TITLE
/stop

### ISSUE THREAD

**Issue by CmD0** [Force-quit/Botlis#2]
We need a way for users to cut the bot mid-play and have it disconnect. This should also get rid of the server's player instance

**Comment by Halzorg** [comment]
I would like to give this issue a go. Could you please assign it to me?

**Comment by Force-quit** [comment]
> I would like to give this issue a go. Could you please assign it to me?

Sure! Welcome. We didn't expect to see anyone here.

**Comment by CmD0** [comment]
@Halzorg you can make your fork and start a feature/stop branch and when you'll be done you can submit a PR back here

**Comment by Force-quit** [comment]
@Halzorg Please complete this issue in 24h or we will do it. We really need this feature as soon as possible. Thank you for your understanding.
